before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: p2FJjwE6fmjecF9gDesAJzX2LN7CTdD4zdKXPZN01nBc3XutGtsoGUIOxivGQ+G31ab6fqtLpvKOW3WLq9XSILBceDHAtCv8U7FTJyVL+5lr8CKwhFpJFfL6EyMJzPrhanTBrUTDjTQG1ZkxsfGXKuXKlLb/jrlOUSvfFAx2i1nJSQQO/baqZJrlMTgjFv2/PmyJtxXgzJzFVoYIMdwjwrlJWx8NsAd0XEbF/ad+YRGDtMlaKIb70u66y5tZ7LYfm9E898SX+BFsL94S/yZmnfrwk6rrYyEieE4ypa6AtKk+9/8HcebkzHx3yFh543fujq5hPw4TVG8dAs4PBPH/8fc4uEwRFAvSz96nIBO0oND82dXiBzeC29SPEZZ92oXIbHyvTuEoyxT1Z79e3v+Xqn2fnhYsln8LILWNwoeDmv6N9bLhAkiKEz4X5zRFsPeuSUX0VbiQ81qJjr3iVp9VFx+U9m+RsnHAC2mj2KUPyA2VHlj0Q6JNZ/YjmDSFKjGNvHw0ZxreAvGJVRow7vzKK3mKmfoxGfXCzUthMCipoP/PEb2Zp7DTXJ6W6ydr7EoUKw4lBBQ+D5x9CZ0N3KcmA54BJYY33ayQCBr+7ptCXUTu6F3MDkgfNMR4IjuqCnDCsSzm2VKH/lpfRdR/+61fcWxwWa04VKB7hVnJj3RIFis= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
